spring:
  profiles:
    active: default

  cors:
    origin: ""

  datasource:
    url: jdbc:mysql://localhost:3306/ecoguia?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration,classpath:db/testdata

springdoc:
  packages-to-scan: com.ecoguia.ecoguia_api.api

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key